server:
    port: 9000
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
spring:
    #  config:
    #    import: classpath:properties/data/auth.yml
    #  config.activate.on-profile: default
    # H2 Setting Info (H2 Console? ???? ?? ???? ??)
    h2:
        console:
            enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
            path: /h2-console  # H2 Console? Path
    # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
    datasource:
        driver-class-name: org.h2.Driver  # Database? H2? ?????.
        url: jdbc:h2:~/test  # H2 ?? ??
        username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
        password:  # H2 ?? ? ??? password ?? (??? ??? ??)
    web:
        resources:
            add-mappings: false
    data:
        jpa:
            repositories:
                enabled: true
    jpa:
        hibernate:
            ddl-auto: create

#logging:
#    level:
#        org.springframework.orm.jpa: trace
#        org.springframework.transaction.interceptor: trace

